### ISSUE TITLE
Google Analytics cookies enabled by default without consent 

### ISSUE THREAD

**Issue by instruccionesaldorso** [websedit/we_cookie_consent#10] opened 2021-01-12 21:59 UTC
Good evening,

It is not very clear to me reading the official documentation  https://consent.websedit.de/fileadmin/consent/daten/dokumentation-we_cookie_consent-en-v1.3.3-20201007.pdf what should be made to avoid the cookies for Google Analytics to be loaded before the cookie consent to be accepted.

I'm using latest version 1.3.3 for the extension and:
1. I created the cookie consent service with "google-analytics" provider.
2. I created the two cookies for my account like shown in the screenshot (specifying a description and lifetime for each one):

![screenshot-2021 01 12-22_42_23](https://user-images.githubusercontent.com/10220356/104378341-23a4fc80-5528-11eb-9e4c-f746c08f4c58.png)

However, I'm not sure which checkboxes should be clicked under "Settings" tab, and I'm not sure which "api_key" should be provided.

Just to notice, this is the code I'm providing to my website: https://developers.google.com/analytics/devguides/collection/ga4

Could you help me with this issue?

**Comment by steinbinder** [comment] 2021-02-10 14:46
Hello, sorry for the late reply. Does the problem still exist? If so, please send us an email to extensions@websedit.de with a note about this ticket. Then we will be happy to help you. Otherwise, I'll close this, as I think it's a configuration error and not a bug.

**Closed by steinbinder** 2021-02-10 14:46 UTC
Labels: question
