### ISSUE TITLE
no privacy policy link for EN

### ISSUE THREAD

**Issue by toccamonium-fe** [websedit/we_cookie_consent#3] opened 2020-09-11 10:24 UTC
Hi,

awesome extension, thx. I just have a problem with the EN version of it as the [privacyPage] placeholder won't be resolved. In the German version it is and shows text and link to proper page. In the locallang.xlf the placeholder was not included, I put it there as I need the link in the banner.

<img width="643" alt="grafik" src="https://user-images.githubusercontent.com/55410878/92911641-5d0a1600-f429-11ea-830f-6c3fb5760f1a.png">

<img width="474" alt="grafik" src="https://user-images.githubusercontent.com/55410878/92911943-a0648480-f429-11ea-904d-98668a8645e0.png">

regards
Florian

**Comment by steinbinder** [comment] 2020-09-23 12:00
I will close this as duplicate of #4

**Closed by steinbinder** 2020-09-23 12:00 UTC
Labels: duplicate
